In [1]:
from data import *
from features import *
from models import *
from utils import *

No GPU found. Using CPU.


In [ ]:
(X_train, y_train), (X_test, y_test), (X_val, y_val) = get_train_test_val_features_and_targets(df=df[:1000], feature_extractor=compute_spectral_features, splits=5, train_size=0.7, test_size=0.15)

In [6]:
# X has to be reshaped into 2D array for sklearn models
X_train = X_train.reshape(X_train.shape[0], -1)
X_test = X_test.reshape(X_test.shape[0], -1)
X_val = X_val.reshape(X_val.shape[0], -1)
print(X_train.shape, X_test.shape, X_val.shape)

(3500, 77) (750, 77) (750, 77)


In [ ]:
# .fit for training and .predict for testing
clf = create_random_forest()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("Random Forest Test Accuracy:", np.mean(y_pred == y_test))
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)
print(clf.feature_importances_) # Feature importance scores -> need to map back to original features
print(np.argmax(clf.feature_importances_))


Random Forest Test Accuracy: 0.3973333333333333
Confusion Matrix:
 [[18  4  1  7  0  7  8 20]
 [ 6 25  2  4 16  8  6 18]
 [ 1  3 39  2 21  6  8  5]
 [11  0  0 50  5 11 15  3]
 [14  4 28  6 34  1  5  8]
 [10  5 13 18  2 42  8  7]
 [ 2  3 10 20  5 22 29 14]
 [ 2  9  7  5  9  8  9 61]]
(8, 8)
[0.01407988 0.01223311 0.01595526 0.00909539 0.01381245 0.00994933
 0.00973068 0.0132272  0.01062745 0.00796639 0.01741023 0.01120315
 0.0124148  0.01051374 0.01497869 0.01880992 0.01276606 0.01453451
 0.01695706 0.01398659 0.01190905 0.01300342 0.01036152 0.01335958
 0.00955048 0.01444773 0.01631037 0.01269945 0.01301912 0.01435419
 0.01330159 0.01162748 0.01554676 0.01122147 0.0131556  0.01025685
 0.01375088 0.0169621  0.01311353 0.01159445 0.01106135 0.01154956
 0.0116885  0.01201533 0.01166333 0.01418406 0.01287996 0.01424538
 0.01439764 0.01233609 0.01191262 0.01301422 0.01318532 0.01307579
 0.01461549 0.01556997 0.01524984 0.01356124 0.01013255 0.0076677
 0.00836194 0.01043644 0.01286894 0.0125