In [1]:
from data import *
from features import *
from models import *
from utils import *

No GPU found. Using CPU.


In [ ]:
(X_train, y_train), (X_test, y_test), (X_val, y_val) = get_train_test_val_features_and_targets(df=df, feature_extractor=compute_spectral_features, splits=5, train_size=0.7, test_size=0.15)

Train size: 700 Test size: 150 Val size: 150


Building train dataset: 100%|██████████| 700/700 [04:22<00:00,  2.66it/s]


3500 700 5


Building test dataset: 100%|██████████| 150/150 [00:56<00:00,  2.64it/s]


750 150 5


Building val dataset: 100%|██████████| 150/150 [00:59<00:00,  2.53it/s]

750 150 5


In [ ]:
# X has to be reshaped into 2D array for sklearn models
X_train = X_train.reshape(X_train.shape[0], -1)
X_test = X_test.reshape(X_test.shape[0], -1)
X_val = X_val.reshape(X_val.shape[0], -1)
print(X_train.shape, X_test.shape, X_val.shape)

(3500, 77) (750, 77) (750, 77)


In [ ]:
# .fit for training and .predict for testing
svm = create_svm()
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
print("SVM Test Accuracy:", np.mean(y_pred == y_test))
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

SVM Test Accuracy: 0.17333333333333334
Confusion Matrix:
 [[ 0  0  5  0  0  0  5  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  5  3  0  7  0  0  0]
 [ 0  0 10  0  0  0  0  0]
 [ 0  7  6  0  2  0  0  0]
 [ 0  0  5  0  0  0  0  0]
 [ 2  0  3  0  0  0  5  0]
 [ 1  0  2  0  3  0  1  3]]
